# Generated by Django 2.0.7 on 2018-12-17 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0002_cinema_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
