# Generated by Django 2.0.7 on 2018-12-17 11:01

from django.db import migrations, models
import fountain.models


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0004_auto_20181217_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=fountain.models.upload_location, width_field='width_field'),
        ),
    ]
