# Generated by Django 2.0.7 on 2018-12-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0007_auto_20181217_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cinema',
            name='published',
            field=models.DateField(null=True),
        ),
    ]
