# Generated by Django 2.0.7 on 2018-12-18 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0008_auto_20181217_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='published',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
