# Generated by Django 2.0.7 on 2018-11-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20181112_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
